services:
  - type: web
    name: tripavail-backend
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start:prod
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4100
      - key: DATABASE_URL
        fromDatabase:
          name: tripavail-postgres
          property: connectionString
      - key: JWT_SECRET
        value: ${JWT_SECRET}
      - key: STRIPE_SECRET_KEY
        value: ${STRIPE_SECRET_KEY}

  - type: web
    name: tripavail-web
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    rootDir: web
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
        value: AIzaSyCTtD2Sl83BYbyDvc_0MU29UxaGc8gQmmQ
      - key: NEXT_PUBLIC_API_BASE_URL
        value: https://tripavail-backend.onrender.com/v1

databases:
  - name: tripavail-postgres
    plan: free
    ipAllowList: []
    databaseName: tripavail
    region: virginia
